#if IG_C111 || IG_C301 // Auto generated by AddMacroForInstantGameFiles.exe

namespace Unity.AutoStreaming.CloudContentDelivery
{
    internal enum ASResourceType
    {
        None = 0,
        StreamedResource = 1,
        AddressableAsset = 2,
        CustomCloudAssets = 3,
        InstantGame = 4
    }

    internal class UOSInfo
    {
        internal static string ApiHost = "https://a.unity.cn/";

        //lanyun backend
        internal static string WcsUploadHost = "unitycdn.up27.v1.wcsapi.com";
        internal static string WcsManageHost = "unitycdn.mgr27.v1.wcsapi.com";
    }
}

#endif  // IG_C111 || IG_C301, Auto generated by AddMacroForInstantGameFiles.exe
